config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "chats#index"
  
  resources :contacts, only: %i(index new create destroy)
  resources :chats, only: %i(index show) do
    resources :messages, only: :create, defaults: { format: :js }
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  belongs_to :record, class_name: "User"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
  validates :content, presence: true
  
  after_create :send_message

  private

    def send_message
      MessageSenderJob.perform_now(self)
    end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable, :rememberable, :validatable 
  
  has_many :contacts 
  has_many :sent, class_name: "Message", foreign_key: "sender_id"
  has_many :received, class_name: "Message", foreign_key: "receiver_id"
  
  has_one_attached :photo
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  before_action :configure_devise_params, if: :devise_controller?
  
  Warden::Manager.after_authentication do |user,auth,opts|
    user.update(is_online: true)
    StatusUpdaterJob.perform_now(user)
  end

  Warden::Manager.before_logout do |user,auth,opts|
    user.update(is_online: false)
    StatusUpdaterJob.perform_now(user)
  end

  protected

    def configure_devise_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:account_update, keys: [:photo, :name, :email, :password, :password_confirmation])
    end
  
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @users = User.joins(:sent).where(messages: { receiver_id: current_user })
    @users += User.joins(:received).where(messages: { sender_id: current_user })
    @users.uniq!
  end
  
  def show
    @user = User.find(params[:id])
    @messages = Message.where(sender: current_user, receiver: @user)
            .or(Message.where(sender: @user, receiver: current_user))
                       .order(:created_at)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = current_user.contacts
  end
  
  def new
    @contact = Contact.new
  end
  
  def create
    user = User.find_by(email: contact_params[:record][:email])
    @contact = current_user.contacts.build(record: user)
    if @contact.save
      flash[:notice] = "Contact succesfully created"
      redirect_to contacts_path
    else
      render :new
    end
  end
  
  def destroy
    @contact = current_user.contacts.find(params[:id])
    if @contact.destroy
      flash[:notice] = "Contact succesfully removed"
    else
      flash[:alert] = "An error ocurred when trying to remove this contact"
    end
    redirect_to contacts_path
  end

  private

    def contact_params
      params.require(:contact).permit(record: :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = current_user.sent.build(receiver_id: params[:chat_id])
    @message.attributes = params.require(:message).permit(:content)
    @message.save
    render :create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chats/index.html.erb
<%= content_for :title do %>
  Chats
<% end %>

<div class="columns is-multiline is-paddingless">
  <% if @users.length <= 0 %>
    <div class="notification is-warning">You don't have any chats started yet. Add a contact and try it!</div>
  <% else %>
    <% @users.each do |user| %>
      <div class="column is-12">
        <div class="columns is-mobile is-vcentered item-list">
          <div class="column is-marginless is-one-fifth has-text-centered">
            <% if user.photo.present? %>
              <figure class="image"><%= image_tag user.photo, class: "is-rounded"%></figure>
            <% else %>
              <i class="fas fa-paw has-text-write-ter"></i>
            <% end %>
          </div>
          <div class="column is-four-fifths">
            <%= link_to user.name, chat_path(user) %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/chats/show.html.erb
<%= content_for :brand do %>
  <% if @user.photo.present? %>
    <%= image_tag @user.photo %>
  <% else %>
    <i class="fas fa-paw has-text-white-ter"></i>
  <% end %>
<% end %>

<%= content_for :title do %>
  <div class="contact-header" data-user="<%= @user.id %>">
    <div class="name">
      <%= @user.name %>
    </div>
    <div class="status">
      <%= @user.is_online? ? "Online" : "Offline" %>
    </div>
  </div>
<% end %>

<div class="message-container">
  <%= render @messages %>
  
  <footer class="send-message has-background-black">
    <div class="container">
      <%= form_with url: chat_messages_path(@user) do |f| %>
        <div class="columns is-mobile is-vcentered">
          <div class="column is-four-fifths">
            <div class="fields">
              <%= f.text_area "message[content]", class: "textarea", rows: 1, style: "resize: none" %>
            </div>
          </div>
          <div class="column is-one-fifth has-text-centered">
            <%= button_tag class: "button is-info is-rounded has-text-white-ter" do %>
              <i class="fas fa-paper-plane"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </footer>
</div>

app/views/contacts/index.html.erb
<%= content_for :title do %>
  Contacts
<% end %>

<div class="columns is-multiline is-paddingless">
  <% @contacts.each do |contact| %>
    <div class="column is-12">
      <div class="columns is-mobile is-vcentered item-list">
        <div class="column is-marginless is-one-fifth has-text-centered">
          <% if contact.record.photo.present? %>
            <figure class="image"><%= image_tag contact.record.photo, class: "is-rounded"%></figure>
          <% else %>
            <i class="fas fa-paw has-text-write-ter"></i>
          <% end %>
        </div>
        <div class="column is-three-fifths">
          <%= link_to contact.record.name, chat_path(contact.record) %>
        </div>
        <div class="column is-one-fifth has-text-centered">
          <%= link_to contact, method: :delete do %>
            <i style="font-size: 1em;" class="fas fa-trash-alt has-text-write-ter"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to new_contact_path, class: "button is-success fab-button" do %>
  <i class="fas fa-plus has-text-write-text"></i>
<% end %>

app/views/contacts/new.html.erb
<%= content_for :title do %>
  New Contact
<% end %>

<div class="columns is-multiline is-paddingless">
  <div class="column is-12">
    <%= form_with model: @contact, local: true do |f| %>
      <%= f.fields_for :record do |uf| %> 
        <div class="field">
          <%= uf.label :email, class: "label has-text-white-ter" %>
          <div class="control">
            <%= uf.email_field :email, class: "input #{ 'is-danger' if f.object.errors[:record].present? }"%>
          </div>
          <p class="help is-danger"><%= f.object.errors[:record].first %></p>
        </div>
      <% end %>

      <%= f.submit "Add Contact", class: "button is-fullwidth is-success is-outlined" %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_sidebar.html.erb
<div id="left-sidebar" class="quickview has-background-black-bis">
  <header class="quickview-header">
    <p class="title has-text-white-ter">
      Menu
    </p>
    <span class="delete" data-dismiss="quickview"></span>
  </header>

  <div class="quickview-body">
    <div class="quickview-block">
      <ul class="sidebar-menu">
        <li>
          <%= link_to chats_path do %>
            <i class="fas fa-comment"></i>
            Chats
          <% end %>
        </li>
        <li>
          <%= link_to contacts_path do %>
            <i class="fas fa-address-book"></i>
            Contacts
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fas fa-cog"></i>
            Settings
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, data: { method: :delete } do %>
            <i class="fas fa-sign-out-alt"></i>
            Sign Out
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-background-black-ter has-text-white-ter">
  <head>
    <title>OneBitMessenger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-widthm initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="has-text-white-ter">
    <% if user_signed_in? %>
      <nav class="navbar has-background-grey-dark has-text-white-ter">
        <div class="container">
          <div class="navbar-brand">
            <div class="navbar-item has-text-white-ter">
              <% if content_for?(:brand) %>
                <%= yield :brand %>
              <% else %>
                <%= image_tag "logo-menu.png" %>
              <% end %>
            </div>

            <div class="navbar-item has-text-white-ter has-text-weigth-bold is-size-5">
              <%= yield :title %>
            </div>

            <div class="navbar-burger burger has-text-white-ter" data-show="quickview" data-target="left-sidebar">
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>

          <div class="navbar-burger burger has-text-white-ter desktop-burger is-hidden-touch" data-show="quickview" data-target="left-sidebar">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
          
        <%= render "layouts/sidebar" %>
      </nav>
    <% end %>

    <section class="section">
      <div class="container">
        <% if alert %>
          <div class="notification is-danger"><%= alert %></div>
        <% elsif notice %>
          <div class="notification is-success"><%= notice %></div>
        <% end%>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="columns is-mobile is-vcentered is-multiline message <%= message.sender == current_user ? 'sender' : 'receiver' %>">  
  <div class="column is-one-fifth-mobile is-1-tablet photo">
    <% if message.sender.photo.present? %>
      <figure class="image is-square is-36x36">
        <%= image_tag rails_blob_path(message.sender.photo), class: 'is-rounded' %>
      </figure>
    <% else %>
      <i class="fas fa-paw has-text-write-ter fa-2x"></i>
    <% end %>
  </div>

  <div class="column is-11-table is-four-fifth-mobile details">
    <div class="columns is-multiline">
      <div class="column is-full content">
        <%= message.content %>
      </div>

      <div class="column is-full date">
        <%= message.created_at.strftime("%m/%d/%Y %H:%M") %>
      </div>
    </div>
  </div>
</div>

app/views/messages/create.js.erb
document.querySelector("textarea[name='message[content]']").classList.remove("is-danger")

<% if @message.valid? %>  
  messageContainer = document.querySelector("div.message-container") 
  messageContainer.innerHTML += "<%= j render("messages/message", message: @message) %>"
  messageContainer.scrollIntoView(false);
  document.querySelector("textarea[name='message[content]']").value = ""
<% else %>
  document.querySelector("textarea[name='message[content]']").classList.add("is-danger")
<% end %>